server:
  port: 7073
spring:
  application:
    name: hwtcp
  rabbitmq:
    host: 172.26.249.105
    port: 5672
    username: admin
    password: test123
    queuename: hwTcpQueue

hwtcp:
  udp:
    port: 4443
  tcp:
    port: 4445